# Generated by Django 4.1.7 on 2023-10-22 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddExpensedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExpenseName', models.CharField(blank=True, max_length=50, null=True)),
                ('Amount', models.IntegerField(blank=True, null=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('ExpenseCategory', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
