# Generated by Django 4.1.7 on 2023-10-22 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addexpensedb',
            name='NAME',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
