# Generated by Django 4.1.7 on 2023-10-22 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0002_addexpensedb_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addexpensedb',
            name='Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
