# Generated by Django 4.1.7 on 2023-10-23 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0004_alter_addexpensedb_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addexpensedb',
            name='Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
