# Generated by Django 4.1.7 on 2023-10-23 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0005_alter_addexpensedb_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addexpensedb',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
