# Generated by Django 4.1.7 on 2023-10-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0007_addexpensedb_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addexpensedb',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
