# Generated by Django 4.1.7 on 2023-10-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0008_alter_addexpensedb_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addexpensedb',
            name='user',
        ),
        migrations.AlterField(
            model_name='addexpensedb',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
