# Generated by Django 4.1.7 on 2023-10-23 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0010_addexpensedb_user_alter_addexpensedb_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addexpensedb',
            name='Amount',
        ),
        migrations.RemoveField(
            model_name='addexpensedb',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='addexpensedb',
            name='ExpenseCategory',
        ),
        migrations.RemoveField(
            model_name='addexpensedb',
            name='ExpenseName',
        ),
        migrations.RemoveField(
            model_name='addexpensedb',
            name='NAME',
        ),
        migrations.RemoveField(
            model_name='addexpensedb',
            name='user',
        ),
    ]
