# Generated by Django 4.1.7 on 2023-10-25 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenseapp', '0012_addexpensedb_amount_addexpensedb_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addexpensedb',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
