# Generated by Django 4.2.6 on 2023-11-28 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenseapp', '0014_alter_addexpensedb_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(blank=True, max_length=50, null=True)),
                ('PHONE', models.IntegerField(blank=True, null=True)),
                ('StreetAddress', models.CharField(blank=True, max_length=50, null=True)),
                ('COUNTRY', models.CharField(blank=True, max_length=50, null=True)),
                ('ZipCode', models.IntegerField(blank=True, null=True)),
                ('UserImage', models.ImageField(blank=True, null=True, upload_to='Media/Userimage')),
            ],
        ),
        migrations.AlterField(
            model_name='addexpensedb',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
